### PR TITLE
Created Tag Input Component

### PR DESCRIPTION
**Pull request by SauceFoong**

### CODE REVIEW

**Comment by Blaise1030** [comment]
@SauceFoong It would be great to have an image attached for us to see how the component looks like

**Comment by NitinMa2** [comment]
@Blaise1030 thanks for the comment! I was helping @SauceFoong refactor his component last night. I have an idea how the component looks.. I'm still waiting for him to add a feature where we can pass in a prop mentioning the limit of the tags. But I agree too, @SauceFoong please attach an image of the component and don't forget to remove the code from the Maintenance page since that was put there for testing purposes.

**Comment by SauceFoong** [comment]
Here you go :) 

Screenshot 2021-07-12 at 7 26 08 PM

**Comment by NitinMa2** [comment]
Great job @SauceFoong xDDD

**Pull request merged**
