### PR TITLE
Adding Vitepress Documentation

### PR DESCRIPTION
**Pull request by NitinMa2**
I have created the Developer Guidelines. To test this, run `npm install` and then execute `npm run docs:dev`. This will open up the documentation in `http://localhost:3000/`.

image

### CODE REVIEW

**Review by shanteru — APPROVED** [review]
So far look neat and good. Documentation really helps me to have an overview of the code :D

**Comment by CheeMinHao** [comment]
I suggest to not merge first since it's not very urgent, can take time to perfect it (there are some bugged out stuff when I had a look)

**Comment by NitinMa2** [comment]
Oh was there a bug? What was it? I think it is important to merge so that it can be referred to during development. I will need the other teammates to refactor their code based on this documentation. The changes should not really affect any existing code.

If there's a bug, I need to look into it. Usually, a page refresh clears a loading issue. We can refine as we progress but it would not be smart to wait until we "perfect" the docs.

**Comment by CheeMinHao** [comment]
I will screenshot some later. Latest by tonight

**Comment by Blaise1030** [comment]
LGTM 🚀

**Review by Blaise1030 — APPROVED** [review]

**Comment by CheeMinHao** [comment]
image

This is one of it so far. Along with I believe a depracting error:

```
DEPRECATION WARNING: Using / for division is deprecated and will be 
removed in Dart Sass 2.0.0.       

Recommendation: math.div($top-nav-height, 1.5)

More info and automated migrator: 
https://sass-lang.com/d/slash-div 

   ╷
59 │ $top-nav-img-height: $top-nav-height/1.5;
   │                      ^^^^^^^^^^^^^^^^^^^
   ╵
    src\common\styles\_variables.scss 59:22  @import
    docs\index.md 2:9
           root stylesheet        

DEPRECATION WARNING: Using / for division is deprecated and will be 
removed in Dart Sass 2.0.0.       

Recommendation: math.div($top-nav-height, 1.5)

More info and automated migrator: 
https://sass-lang.com/d/slash-div 

   ╷
59 │ $top-nav-img-height: $top-nav-height/1.5;
   │                      ^^^^^^^^^^^^^^^^^^^
   ╵
    src\common\styles\_variables.scss 59:22  @import
    src\common\styles\_font.scss 3:9         @import
    docs\index.md 2:9
           root stylesheet        

DEPRECATION WARNING: Using / for division is deprecated and will be 
removed in Dart Sass 2.0.0.       

Recommendation: math.div($top-nav-height, 1.5)

More info and automated migrator: 
https://sass-lang.com/d/slash-div 

   ╷
59 │ $top-nav-img-height: $top-nav-height/1.5;
   │                      ^^^^^^^^^^^^^^^^^^^
   ╵
    src\common\styles\_variables.scss 59:22  @import
    src\common\styles\_font.scss 3:9         @import
    docs\index.md 2:9
           root stylesheet        

DEPRECATION WARNING: Using / for division is deprecated and will be 
removed in Dart Sass 2.0.0.       

Recommendation: math.div($top-nav-height, 1.5)

More info and automated migrator: 
https://sass-lang.com/d/slash-div 

   ╷
59 │ $top-nav-img-height: $top-nav-height/1.5;
   │                      ^^^^^^^^^^^^^^^^^^^
   ╵
    src\common\styles\_variables.scss 59:22  @import
    src\common\styles\_mixins.scss 2:9       @import
    docs\index.md 2:9
           root stylesheet        

DEPRECATION WARNING: Using / for division is deprecated and will be 
removed in Dart Sass 2.0.0.       

Recommendation: math.div($top-nav-height, 1.5)

More info and automated migrator: 
https://sass-lang.com/d/slash-div 

   ╷
59 │ $top-nav-img-height: $top-nav-height/1.5;
   │                      ^^^^^^^^^^^^^^^^^^^
   ╵
    src\common\styles\_variables.scss 59:22  @import
    src\common\styles\_mixins.scss 2:9       @import
    docs\index.md 3:9
           root stylesheet        
```

Besides that all good to go!

**Comment by NitinMa2** [comment]
Hmm I see that this issue is to do with the codebase itself and not the documentation. Also, the image is not a bug but it was intended to be like that. I guess I shall merge the branch for now and add the deprecation as a task in our backlog! Thanks for catching that :)

**Comment by CheeMinHao** [comment]
ahhh alright! I guess that color section could be improved but after your explanation, I have no further questions and will be merging the code now. Thanks for the clarification!

**Pull request merged**
